### ISSUE TITLE
instructor guide should contain tips on how to introduce lesson

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-collaborative#102]
e.g. by drawing a diagram on the whiteboard introducing a remote, e.g. github, and the local repo on laptop, with arrows between which represent cloning, pulling/fetching, pushing.

**Comment by joasilva** [comment]
> e.g. by drawing a diagram on the whiteboard introducing a remote, e.g. github, and the local repo on laptop, with arrows between which represent cloning, pulling/fetching, pushing.

Definitely, instead of jumping directly to the slides.

**Comment by wikfeldt** [comment]
i forgot to take a picture of the nice drawing that Radovan made this morning, but we can recreate it for the instructor guide

**Comment by bast** [comment]
This is a good suggestion but now the intro episode contains a number of figures so hopefully this is now less dry.
