### ISSUE TITLE
Quick reference not created yet

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#104]
It should be created, currently it is a dead link.

**Comment by rkdarst** [comment]
I'm thinking to not create another one here, but just to link directly to the git-intro one and improve that (and make a new section for collaborative stuff there).  Otherwise, we end up duplicating the intro part in this repo.  What do you think?

But, we currently can't link directly to a reference in another repo.

**Comment by rkdarst** [comment]
created, minimally works.  Once someone else reviews, then this issue can be closed.

- I'm sure some stuff is missing.
- It doesn't duplicate all the git-intro stuff.  It would be reasonable to move all of this info to git-intro (in a separate supersection specifically labelled as "for collaborative git"), and then just link to there.

**Comment by bast** [comment]
Closing. Now there is something there. It can always be improved. Now pruning issues to improve focus on really broken things.
