### ISSUE TITLE
Split first episode into two

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#111]
Coming up in 10-20 mins ... @annefou 

Motivation: will make it easier for us to work in parallel but also it can be taught in two sessions then.

**Comment by joasilva** [comment]
I'm having issues in production that need to be solved ASAP, so unfortunately I can't join in today :-( 

//JMS

**Comment by bast** [comment]
> I'm having issues in production that need to be solved ASAP, so unfortunately I can't join in today :-(

No problem and good luck!
