### ISSUE TITLE
The centralized workflow episode will be turned around

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#112]
Instead of starting with working on the master branch and experiencing trouble and leaving participants with a bad feeling about collaborative Git, we start with branches right away, show how to update master, and later can discuss what would have happened if we all worked on master.

Also we need to communicate better that centralized workflow is a perfectly fine setup for most projects.

**Comment by bast** [comment]
Taking this over. It's probably already implemented but need to check.

**Comment by annefou** [comment]
@bast yes it should be done too. I simply forgot we had an issue. Let me know if it does not work as expected.

**Comment by bast** [comment]
Anne solved it. Closing.
