### ISSUE TITLE
Work on "remotes" episode

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#114]
This is the first episode to get participants up to speed with concepts needed:
- What are Git clone, pull (fetch), push (we may have seen them in Git intro but we can assume that some participants have not followed Git intro)
- Also mention what is forking, importing, generating but we don't have to spend time on these, just to have them in one place and we can return to a comparison
- Give examples for when forking, importing, generating can be useful
- Lots of pictures instead of lots of text (but also text for accessibility reasons)

**Comment by blindij** [comment]
A principle I am trying to stick to with remotes is to use "upstream" for the original repository that is forked, then my forked repository as "downstream". I imagine that I am "fishing"(working) in between. As I am done with my work, I go "downstream" and make a PR.

I am using "origin" if I have only a my own repository, typically a private one, or something that is not forked.

I said this during the last Workshop, and it clarified the remotes for some, but fogged it for others.

**Comment by bast** [comment]
Some images added in #133. I did not address the "upstream" part but perhaps that can be introduced in the forking part?

**Comment by bast** [comment]
I think this has been addressed in #133.
