### ISSUE TITLE
try to make the forking-workflow exercise more collaborative 

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-collaborative#125]
in online workshops participants are sent to breakout rooms for the forking workflow exercise, but without specific discussion points maybe some rooms become quiet and learning from collaborating gets lost

**Comment by bast** [comment]
Yes I had the same impression. I was encouraging participants to start sharing screen and ask questions and eventually we got a good discussion but just following the exercise itself it would have been silent and a long 30 minutes.

**Comment by bast** [comment]
@blindij see also #124. Maybe not enough time to change the material but we need to at least verbally give tips on how to turn this more collaborative. I am working on the centralized episode so that you can focus on this part.

**Comment by bast** [comment]
I will keep the exercise but make more clear when to return from the exercise. The review of PRs we will do in the main room so the exercises will be shorter and there should not be any waiting time for those who finish earlier.
