### ISSUE TITLE
General feedback from a workshop based on Git-Collaborative

### ISSUE THREAD

**Issue by yuanxiesa** [coderefinery/git-collaborative#143]
Hi,

Lately, I ran a workshop using your material. The overall feedbacks were positive. And I appreciate that you developed this class. I will give a list of suggestions in the following issues, and I will work on some of the suggested improvement on my fork as well. 

Thanks again!

**Comment by bast** [comment]
Super! Thank you! Can you please give us a link to the course where you used it? We would like to compile a list of places where this was used which would be very good for my reporting to the funding bodies of our project.

**Comment by yuanxiesa** [comment]
Yes. Can you give me an email address? I prefer sending the info via email.

**Comment by bast** [comment]
radovan.bast@uit.no

**Comment by bast** [comment]
Closing this since we have followed-up on this via email. I am working on the other issues.
