### ISSUE TITLE
Adding instructions about how to do the demo

### ISSUE THREAD

**Issue by yuanxiesa** [coderefinery/git-collaborative#144]
In the class, because the instructor or the helper will be the owner of the repo, this person can no longer demo many of the operations as the students. There are two solutions. First, the owner can have a second account and demo from it. Second, the owner can have one of the students to share the screen. My experience is that the second one is better in remote learning, and the first may be better in face-to-face instruction. I would suggest to clarify this situation and state possible solutions.

**Comment by bast** [comment]
Thanks! Indeed. Also leaning towards the second. It's fun to switch between screen-shares as this clarifies changing context.
