### ISSUE TITLE
Do we demonstrate push-to-master workflow anywhere in the workshop?

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#152]
Despite all we say, I expect most people to push to master more often than they go by pull requests, if nothing else because more projects are solitary than collaborative.  Do we have an exercise about this anywhere, or have people practice this?  Should we?  I think we should, when we go straight to PR-based workflow we are missing a lot!

I know we mention it in the "levels of git complexity" in git-intro, but it's an abstract, not-yet-demonstrated concept at that point.  There is also the "sharing repositories online" in git-intro, but that doesn't go to the point of useful collaboration.

What to do about it: I'm not sure.  Maybe make an optional episode before the centralized workflow that just does this - one we never give, but people can read later.  We used to have this as a example before we got to PRs, but not anymore.

**Comment by rkdarst** [comment]
To be clear, I don't think we should do something about this for tomorrow.

**Comment by bast** [comment]
There is this: https://coderefinery.github.io/git-collaborative/02-centralized/#exercisediscussion-why-did-we-create-a-feature-branch-yourname-somefeature but this is probably not what you mean

**Comment by rkdarst** [comment]
OK, yes, that does explain the idea minimally, which is good.  I wish we could demonstrate and explain more, but I realize we haven't gone that direction.

Anyone reviewing this in the future: it's OK if this is closed without much action.

**Comment by bast** [comment]
I think we can still emphasize more that working with the default branch only can be fine at the beginning/ for own projects.
