### ISSUE TITLE
practical git PRs

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#154]
Recently I made this:
https://scicomp.aalto.fi/scicomp/practical-git-prs/

could it be of any use?  I have a feeling it could be linked somewhere...

**Comment by bast** [comment]
This is great!

**Comment by rkdarst** [comment]
some material could be copied in, but maybe it's better to link (mainly, the different roles that PRs can play).

**Comment by bast** [comment]
A must-be-linked. I will link it somewhere and later we can borrow some text.
