### ISSUE TITLE
"template for hackmd" for the gorup sessions has private info in public document

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#155]
The hackmd template is nice, but lately we are sharing the document basically publically.  should it be there?  Or maybe, just remove the username part and have people share it via chat.

**Comment by rkdarst** [comment]
Also, by making a new section for each team, the list gets very long and then it's hard to get an overview of how teams are doing.  A bullet list is better for the "overview to organizers" part (in addition to this).  

This is a random thought, but I don't think it should affect the design of this template section.

**Comment by bast** [comment]
Yes we should reword to communicate this via chat.
