### ISSUE TITLE
is "git checkout -b somefeature origin/somefeature" ever useful?

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-collaborative#160]
in:
https://coderefinery.github.io/git-collaborative/02-centralized/#discussion-how-to-make-changes-to-remote-branches
it says:
We can create a local branch somefeature tracking origin/somefeature:
$ git checkout -b somefeature origin/somefeature

this only works if there is a remote branch `origin/somefeature`, and in that case `git checkout somefeature` is always enough. 

I think this can be confusing

**Comment by bast** [comment]
I always use the shorter form for this case but the longer form can be useful when one works with multiple remotes. I found the short form surprising the first time I saw this (I think I found this out by accident).

Maybe this explanation is indeed more confusing than helpful.

**Comment by wikfeldt** [comment]
maybe less risk of confusion if we clarify that the long form is for unambiguity in case of multiple remotes. I'll add something

**Comment by wikfeldt** [comment]
ironically i accidentally "pushed to master" in 82aae27 to solve this issue, will let it slip this time...
