### ISSUE TITLE
Idea for new content: adding code reviews to git-collaborative 

### ISSUE THREAD

**Issue by sunnivin** [coderefinery/git-collaborative#167]
# Code reviews as a part of git-collaborative?  

Inspired by your excellent workshops and templates I have made a lesson for code reviews through the Github interface and tested it on a workshop with my colleagues. I was wondering if you are interested in reusing/adding some of the content to make your great lesson event better? I designed the lesson to be half a day, but I think it should be compressed a little if you want to add some of the parts to your work. If you are interested I'm happy to do that. 

You may find the lesson [here](https://sunnivin.github.io/lesson-code-review/).   

P.S. Please let me know if I have not used the credit or license correctly so I can fix it. It would not have been possible for me to make this lesson without building on top of your great work!

**Comment by bast** [comment]
Thanks! This is super interesting!

Indeed we are planning an event late Feb with focus on code review and this would be a great opportunity to integrate this. I will have a more detailed look soon and I am sure we will be super happy to get this into the material.

About the credit/license: we still need to streamline this on our side to make it easier to reuse and for contributors to get credit and visibility.

**Comment by sunnivin** [comment]
Great to hear! 

I will be happy to help with cutting/changes of the material if needed. If you let me know how and what you would like to keep I will file you a PR!

**Comment by sunnivin** [comment]
Let me know if you like a hand!

**Comment by bast** [comment]
Yes. Let's collaborate on that. I plan to pick it up "as soon things calm down a bit" (will they ever? ... after the workshop).

**Comment by bast** [comment]
I am now finally working on this again. My plan is to teach it in two weeks. So hopefully I will manage to incorporate this.

**Comment by sunnivin** [comment]
> I am now finally working on this again. My plan is to teach it in two weeks. So hopefully I will manage to incorporate this.

💯 🥳

**Comment by bast** [comment]
Unassigned myself since I am too busy preparing other lessons that need more work. We now have an episode on code review but somebody should still go through Sunniva's excellent material and identify what we are missing in CR lesson and merge/incorporate.

**Comment by Sabryr** [comment]
@sunnivin Hello, I am planing to teach this lesson and noticed this issue, did you already commit any material to CR ? could you please point me to the contributions you were referring.

**Comment by sunnivin** [comment]
Cool that you are still sharing git to the people 😄 

The material I referred to in the issue is [here](https://github.com/sunnivin/lesson-code-review). I made it like a lesson to have a focus day with my team about collaboration and git. And introduce some standard tools/techniques to make the cooperation easier. 

It is a while ago, so for example, the style of the lesson is outdated. I did not push anything to the code refinery lesson because I did not know if you were interested in expanding the content. 

If you do not think this subject fits into your teaching schedule I guess it makes sense to close this issue.

**Comment by sunnivin** [comment]
Or, maybe the content could fit under *Optional episodes*.

**Comment by Sabryr** [comment]
Thank you

**Comment by Sabryr** [comment]
Refereed to the material and I think most of the concepts have been already covered in https://coderefinery.github.io/git-collaborative/code-review/. So I am closing this issue than you for your contributions.
