### ISSUE TITLE
Introducing fork, clone, templates in the introduction can be overwhelming for the learners

### ISSUE THREAD

**Issue by niketagrawal** [coderefinery/git-collaborative#173]
[The figures in the introduction](https://coderefinery.github.io/git-collaborative/01-remotes/#commits-branches-repositories-forks-clones) briefly introduces several terminologies and concepts in one go: fork, clone, templates. This can be a bit overwhelming for the learners at the start as the details come only in the 2nd half of the session. There were already questions from learners in the HackMD asking the difference between clone and fork in the first 10 minutes of the workshop. This can be avoided with a little restructuring.

Suggestion: The figures already do a good job at connecting the concepts together! They are better suited to use in the summary rather than at the start. When introducing concepts at the start, focus on one concept at a time, modify the existing figures to align with this. 

An example teaching workflow could be:
1. Concept to introduce: clone 
Objective/Context: How to collaboratively work in a relatively small group where everyone has access to the git repository?

2. Concept to introduce: Fork
Objective/Context: How to contribute to a git repository to which you don't have access to?

Hopefully, this can help learners to get a better understanding of the concepts and the context in which they can be used.

**Comment by bast** [comment]
Thanks Niket for these good suggestions and for writing them down!

**Comment by bast** [comment]
This is perhaps related to #206 @Sabryr ?

**Comment by bast** [comment]
Figures are now here: https://coderefinery.github.io/git-collaborative/remotes/

**Comment by MatiasJJ** [comment]
• Template-topic could be in somewhere else – eg. optional episodes?
• First talk about cloning and then forking separately
• Include the "syncing between places" in where the clones and forks are discussed
