### ISSUE TITLE
Improve motivation (notes)

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-collaborative#206]
Currently some term descriptions are not fully accurate and some not too intuitive nouns are present

    Sharing by email or manually: isn’t fun and doesn’t scale, projects are limited to the time and cognition of one person.  : **Rephrase cognition** . time could be a factor when using Git as well

    One person’s repository on the web: allows one person to keep track of more projects, gain visibility, feedback, and recognition.

    Centralized: everyone can directly update the same repository. Good for small groups.

    Distributed: anyone can suggest changes, even without advance permission. Maintainers approve what they agree with. **I do not think distributed means this ** it means many independent linked/linkble copies or something. When local copies are made of a Centralized repo or a personal repo, then it is distributed as well

**Comment by Sabryr** [comment]
Explain what **transformative** means

**Comment by Sabryr** [comment]
Without contributing any code, reviewing a pull request could account to contribution. Improving README is  a contribution

**Comment by Sabryr** [comment]
Following is excellent "tag .. Like a sticky note that you attach to a particular commit" . This is the level we should target here

**Comment by Sabryr** [comment]
Generating from templates and importing - may be move this to later

**Comment by Sabryr** [comment]
Another good and simple explanation of an important concept: **...development line and this is marked as “central”. The “central” is a role, not a technical difference.**

**Comment by Sabryr** [comment]
See if collaboration  can be requested, rather than we add them

**Comment by bast** [comment]
If you are working on this, can you please self-assign? If some of the ideas do not get implemented, can you please create self-contained issues so that somebody else in 6 months can pick it up? Thank you.

**Comment by bast** [comment]
> See if collaboration can be requested, rather than we add them

It does not seem so.
