### ISSUE TITLE
`git graph` after each exercise step

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#222]
Should we define `git graph` again in this lesson, and suggest `git graph` after each step?  If you ask me, this is useful since it is how I keep an understanding of how things are changing.

**Comment by bast** [comment]
It's worth adding it and I would add it as suggestion on top of each exercise but I don't think we should make the pages longer by also adding the output from `git graph` (and I know this is not what you suggested).

**Comment by rkdarst** [comment]
Yeah, definitely not show all that output (that's already in the graphs).  Colud be
```console
$ git graph      # if you want to check where you are
```
after every step, to drive the point home (but not show the output)?

Mentioning in the exercise descriptions probably sufficient, too!  It could even mention to run the three basic status commands each time: `git graph` (always), `git status` (when needed), and if relevant `git diff` and `git dif --staged`  Hm.... I can work on this.
