### ISSUE TITLE
Why do we create a fork?

### ISSUE THREAD

**Issue by rantahar** [coderefinery/git-collaborative#242]
I'm not sure this is clear from the current material (feel free to disagree :) ).

In my mind there are two reasons:
  - We cannot edit the central repository (clearly explained in the material)
       - but for this, we could just clone and make our changes
  - The maintainer needs something to pull from. They cannot pull from my laptop if it's closed.
  - The cloud provider is a trusted place to pull from and allows review before pulling.

**Comment by bast** [comment]
Good points! Another motivation for forking would be to keep the central repo tidier.
