### ISSUE TITLE
Update detailed schedule

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#252]
This was the schedule from March 2023:

* 08:50 - 09:00 Soft start and icebreaker question
* 09:00 - 09:15 Recap Git, any Hackmd questions to highlight
  - 09:15 - 09:30 Concepts around collaboration
    1. Explain terms. Pull, push, clone, fork. Focus on pull and not fetch.
    2. Focus more on Clone and less on Generating from templates and importing
  - 09:30 - 11:10 Centralized workflow + a break
    - 9:30 - 9:45 : Explain concepts.
    - 9:45 - 9:55 break
    - 9:55 - 10:00 Inform clearly what is expected outcome.
    - 10:00 - 10:30 Exercise
    - 10:30 - 10:50 Instructors go through the exercise
    - 10:50 - 11:00 - break
  - 11:00 - 12:10 Distributed version control and forking workflow + one breake
    - 11:00 - 11:15 - Concepts and what are exercise outcomes
    - 11:15 - 11:45 - Exercise
    - 11:45 - 12:00 - Instructors go through excercises
    - 12:00 - 12:10 - break
  - 12:10 - 12:30 - How to contribute changes to somebody else’s project and Q&A

**Comment by dhanyapushpadas** [comment]
**New Schedule for September 2023**

* 08:50 - 09:00 Soft start and icebreaker question
* 09:00 - 09:15 Recap Git, any Hackmd questions to highlight
  - 09:15 - 09:30 Concepts around collaboration
    1. Explain terms. Pull, push, clone, fork. Focus on pull and not fetch.
    2. Focus more on Clone and less on Generating from templates and importing
  - 09:30 - 11:00 Centralized workflow + a break
     - 9:30 - 9:45 : Explain concepts.
     - 9:45 - 9:55 break
     - 9:55 - 10:00 Inform clearly what is expected outcome.
     - 10:00 - 10:30 Exercise
     - 10:30 - 11:00 Instructors go through the exercise
  - 11:00 - 12:00 - Lunch break
  - 12:00 - 13:10 Distributed version control and forking workflow + one breake
     - 12:00 - 12:15 - Concepts and what are exercise outcomes
     - 12:15 - 12:45 - Exercise
     - 12:45 - 13:00 - Instructors go through excercises
     - 13:00 - 13:10 - break
  - 13:10 - 13:30 - How to contribute changes to somebody else’s project and Q&A

**Comment by dhanyapushpadas** [comment]
MR here https://github.com/coderefinery/git-collaborative/pull/255
