### ISSUE TITLE
Switch to "main" as default branch

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#254]
This is dependent on https://github.com/coderefinery/git-intro/issues/352

If we change to "main" as default, please check all screenshots and graphics.

**Comment by dhanyapushpadas** [comment]
I will work on the text.

**Comment by johanhellsvik** [comment]
and I will revise the figures

**Comment by bast** [comment]
Let me know if you need help with the box-arrow-figures. It is easy for me to regenerate them but maybe less easy for those who don't know the program (I wrote that little tool).

**Comment by johanhellsvik** [comment]
Aha, I see. I had planned to use Inkscape - but can try out the tool that you have created.

**Comment by bast** [comment]
Yes, please consider svg to be the generated result. It is better to change the sources (the txt files).

**Comment by dhanyapushpadas** [comment]
@bast I see that it is still master on intro lessons. I assume that it will be changed. On git collaborative text, how do you suggest , remove all mention of master or say main or master.

**Comment by bast** [comment]
> @bast I see that it is still master on intro lessons. I assume that it will be changed. On git collaborative text, how do you suggest , remove all mention of master or say main or master.

Yes I did not manage yet but please assume it will happen this week.
I recommend:
- mention "main" instead of "main or master"
- however please also assume that somebody joins day 3 and hasn't been there on day 1 or 2 so add a step where we get everybody on the same page

**Comment by dhanyapushpadas** [comment]
texts are changed  accordingly https://github.com/coderefinery/git-collaborative/pull/259.

**Comment by johanhellsvik** [comment]
Remaining work:
Update 'master' to 'main' also in GitHub screenshots. Editing with a drawing program blurred the original screenshots, wherefore new screenshots would be desired.
Adjust the positioning of boxes in content/img/centralized/04-local.svg, content/img/centralized/06-local.svg and content/img/centralized/07-local.svg in order to avoid overlap.
