### ISSUE TITLE
Please use "git switch" instead of "git checkout"

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#256]
- see: https://github.com/coderefinery/git-intro/issues/326
- `git switch` instead of `git checkout` (when switching branches)
- `git switch --create` instead of `git checkout -b`

@johanhellsvik @dhanyapushpadas for info

**Comment by bast** [comment]
I can send the PR if you want but I wanted you to be aware of it to not create confusion and to align with days 1 and 2.

**Comment by dhanyapushpadas** [comment]
Thanks @bast. I will do it as part of the preparation.
