### ISSUE TITLE
Consider moving last break to a bit earlier

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#257]
https://coderefinery.github.io/git-collaborative/guide/

Break could be before discussion
- advantage: those who finish earlier can go to break earlier, second half is not just 20 minutes but 30 or 35 minutes, break is more "in half"
- disadvantage: there is risk that break is not taken but used for exercise

@dhanyapushpadas @johanhellsvik you decide what you like better but this is what I thought when studying your schedule.

**Comment by bast** [comment]
Here talking about the "13:00 - 13:10: break"

**Comment by dhanyapushpadas** [comment]
Thanks for the suggestion @bast.
@johanhellsvik  Shall we change the second half as suggested. If so I will change it as follows later today. Thanks.
12:15 - 12:45: [Exercise](https://coderefinery.github.io/git-collaborative/distributed/#exercise-preparation)
12:45 - 13:55: Break
13:00 - 13:10: Instructors go through excercises. Discussion and answering questions
13:10 - 13:30: [How to contribute changes to somebody else’s project](https://coderefinery.github.io/git-collaborative/contributing/) and Q&A

**Comment by johanhellsvik** [comment]
I agree to the suggested change.
