### ISSUE TITLE
Timing in instructor guide is old and points to renamed pages

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#283]
This is outdated: https://coderefinery.github.io/git-collaborative/guide/#schedule-day-3

In March 2024 we introduced pull requests already on day 1 and 2 and therefore, on day 3 we could go a bit deeper and assume that learners have already opened and seen pull requests. Here we could focus more on the collaboration and code review aspect.

**Comment by bast** [comment]
The exercises have reasonable timings and I would try to reverse-engineer overall timing from them. Sorry that this isn't clearer.

**Comment by bast** [comment]
We went through "CORE LESSON".
We did not go through "OLDER EPISODES" (I would remove those).
We did not go through "OPTIONAL EPISODES".

**Comment by bast** [comment]
Good timing information can be found here: https://github.com/coderefinery/2024-03-12-workshop/blob/main/video-editlist.yaml

**Comment by bclaremar** [comment]
This is what I get from the above times
(I'll update this with subsection timings as well)

- 08:50 - 09:00 Icebreaker 
- 09:00 - 09:15 Recap and Intro
- 09:13 - 09:30: [Concepts around collaboration](https://coderefinery.github.io/git-collaborative/concepts/)	**10 min**
- 09:30 - 11:00: [Collaborating within the same repository](https://coderefinery.github.io/git-collaborative/same-repository/)		**70 m incl break**
- Lunch
- 12:00 [Practicing code review](https://coderefinery.github.io/git-collaborative/code-review/)				**10 min**
- 12:10 [How to contribute changes to repositories that belong to others](https://coderefinery.github.io/git-collaborative/forking-workflow/)	**56 min**
- Break
- 13:00  Q/A						**30 min**
