### ISSUE TITLE
Instructor instructions

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#35]
- [x] ensure the instructor or someone there has access to add collaborators to the CR centralized-workflow-exerciserepo.  You can use a fork but people will use the wrong one (unless the instructions are updated) and it will be a big mess!
- [ ] People really have to sit next to someone, so that they can see the screens.  From the beginning.
- [ ] Emphasize use of `git graph` a lot, just like in git-intro

This issue will be edited.

**Comment by bast** [comment]
First point taken care of in #44.
