### ISSUE TITLE
ssh key generation and usage

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#36]
This seems to be missing.  This is probably the best place to put it, not git-intro.

By the way, mac laptops worked the same as linux - ssh-agent was automatically running and you could just `ssh-keygen` with password and `ssh-add` and it Just Works.  Remind people to run ssh-add next time (unless it automatically adds these days).

**Comment by bast** [comment]
For simplicity we only use https but I will add links that describe how to set up keys.
