### ISSUE TITLE
Non-bare and bare repositories - Instructions are incomplete. 

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-collaborative#37]
There is a statement "Clone this repository on the same computer with either --bare or --mirror" and not enough guidance given

**Comment by bast** [comment]
Where is this statement? Can you post a link?

**Comment by Sabryr** [comment]
https://coderefinery.github.io/git-collaborative/02-bare-repos/

**Comment by bast** [comment]
I have skipped that part last time and recommend to skip it (you can add a note in the guide). The only thing I said that it is possible to host and share a Git repository on your own desktop or cluster and if you are interested in that, have a look at bare/nonbare. No need to go into that.
