### ISSUE TITLE
consider teaching this lesson not first thing in the morning

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-collaborative#47]
for the reason that if someone shows up late then it's complicated to get them up to date (i.e. adding to the centralized-workflow-exercise). After lunch or starting mid-morning might be better

**Comment by bast** [comment]
We could start with modular code development or reproducible research in the morning and have the collaborative Git lesson go across the lunch break. I think we should either try it or drop this issue.

**Comment by bast** [comment]
Yes, we need some time padding before this session - this does not work well with some participants arriving late. Would be good to have a short session of something else first.

**Comment by rkdarst** [comment]
I guess this can be closed, since reproducible research, since this has been done with all future workshops.  Please re-open if wrong.  Also re-open if we have a place where "typical" schedule is documented.

**Comment by bast** [comment]
I agree this is now moved. We don't have a central place with a typical schedule (AFAIK) yet - I normally reuse a schedule from a past workshop which worked well.
