### ISSUE TITLE
Mention "git describe"

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#5]
Example: `git describe --abbrev=7 --long --always --dirty=-feature_smudge-clean`.

basically it describes the current state of the repo using the closest tag in history.
so assuming you tag meaningfully what you'd read from a git describe is:
closest tag followed by number of commits current revision has on top
followed by SHA1 of current commit (abbreviated by default)
optionally, if you're in a dirty state you can add a suffix with --dirty
(which by default add -dirty, but you can choose whatever).

(thanks to Roberto for the hint!)

**Comment by robertodr** [comment]
In particular, that command on one of my projects returns: `v1.1.7-8-g2d03836-feature_smudge-clean`
Closest tag is `v1.1.7`, I have 8 commits on top of that, last commit has abbreviated SHA1 `g2d03836`, I have some work staged and/or unstaged for commit.

**Comment by bast** [comment]
I think this is a good idea but after some thoughts I feel it is a bit too advanced for the course - I think this would make a great blog post, though. My goal is that people understand branches and tags after the course and if they do, they can go out in the world and explore things. But thanks for the suggestion - I did not know this command before.
