### ISSUE TITLE
consider adding origin/HEAD pointer to graphics

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-collaborative#50]
because it actually exists. Clarify also why it's there

**Comment by bast** [comment]
Yes - we could have it there and this determines the default branch.

**Comment by bast** [comment]
I am unsure whether we should add it. It will make the figures heavier and possibly distract. How about we leave it out and in case the question comes up (it came up only once) we discuss it? I could add something about it to the instructor guides.

**Comment by Sabryr** [comment]
Arrow could cause confusion between    "direction of travel" and "parent commits"

**Comment by bast** [comment]
I will not add this to not overload the figures but I am adding a note to the instructor guide.
