### ISSUE TITLE
clarify how e.g. github is both bare and non-bare repo

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-collaborative#51]
it can be confusing since we do make a commit directly on github in the git-intro demo

**Comment by bast** [comment]
I think I would not go there - I think it's complicated and I would avoid it but also the thing to avoid is to even mention that GitHub is a bare repo which I did last time.

**Comment by bast** [comment]
I think what we have in the material is correct - the repositories are stored as bare repos. How they implement the web frontend editing I don't know but I doubt this is actually a non-bare repo. Closing.
