### ISSUE TITLE
Check whether bare/nonbare episode is still needed

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#70]
I just did few tests on my hard drive with bare/nonbare and some of my assumptions about it were wrong. I need to test a bit more but possibly we can avoid that part all together. Opening this issue so that I won't forget.

**Comment by bast** [comment]
I recommend to skip/drop this episode.

**Comment by rkdarst** [comment]
Agree... it would be useful for a later practical advice section but for its current position, unnecessary complexity.

Showing that "any ssh server can become a git remote" is a good thing to teach, and could even become an exercise.

**Comment by bast** [comment]
I can send a PR removing this episode if @blankdots agrees.

**Comment by blankdots** [comment]
ok :+1: - Or we can have it optional ?

**Comment by bast** [comment]
OK I will do the following:
- in instructor guide mention that this is optional
- move this as last episode to prevent instructors who are not super familiar with the material to "waste time" trying to teach this (I never had time to do this)
