### ISSUE TITLE
Cannot delete repositories in coderefinery

### ISSUE THREAD

**Issue by annefou** [coderefinery/git-collaborative#71]
The lesson requires to be able to delete two repositories before a workshop:

-  https://github.com/coderefinery/centralized-workflow-exercise
- https://github.com/coderefinery/forking-workflow-exercise

I cannot delete these two repositories.

This method forbids us to have several workshops simultaneuously and also requires anyone to get access to coderefinery organization.

Should we prefer each of us to import the template repositories to our own github username?

**Comment by wikfeldt** [comment]
good catch, yeah this does not work for simultaneous workshops and also not for people without write permissions under coderefinery org. I think the recommended procedure for instructors should be to import to their own github username and add the learners to that repo instead. i see that in _config.yml one can set centralized_workflow_exercise_url and forking_workflow_exercise_url to point to the correct (imported) repos

**Comment by bast** [comment]
- own namespace is a solution but we then also need to update links on the workshop page
- we can modify the instructions that org owners remove these repos
- don't think that we will have 2 "official" coderefinery workshops at the same time soon, but i hope i am wrong :-) (for "spin-off" workshops it is natural to import this into another namespace)

**Comment by bast** [comment]
I will make more clear in the instructor guides that the exercise repositories need to be not only created but also destroyed later, otherwise the next instructor may not have the permissions to delete them.
