### ISSUE TITLE
automated testing for forking-workflow-exercise is missing if instructor mirrors to own github namespace

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/git-collaborative#72]
i think we used to have coderefinery/forking-workflow-exercise connected to Travis, so that we could see the red/green lights on the PRs. This was nice as it gave a hint of what was to come in the testing lesson. Probably we should add to instructor notes that the mirrored repo should be connected to travis

**Comment by bast** [comment]
Travis setup is mentioned here: https://coderefinery.github.io/git-collaborative/guide/#prepare-exercise-repositories

But maybe needs to be reworded or clarified.
