### ISSUE TITLE
Episode 03-distributed type-along doesn't need to be in a group

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#73]
It seems that the type-along in 03-distributed doesn't need to be done in a group.  In fact, while helping I was confused because it took some time for me to figure out why it said to break into groups... it was something in automated testing that did the mutual forking and accepting of PRs.

**Comment by rkdarst** [comment]
Speaking of which, each exercise/type along should have a summary at the top explaining what is happening, so that a helper can just read that and understand what the goal is.  That was missing in some places, which made my helping less effective because I had to figure out the point myself first.  (This should be documented elsewhere, perhaps in lesson design manual...)

**Comment by bast** [comment]
I agree that this point confused many participants in the past. The only motivation to work in groups was to help each other out but perhaps it's simpler if everybody types but we encourage participants to discuss.

**Comment by bast** [comment]
If the material is adjusted to work individually - which I recommend - we need to also change the naming. `group-13.py` will then not make sense anymore.

**Comment by rkdarst** [comment]
Yes... at that level, everything should be group work (always sit next to someone and discuss as you are doing the exercises), at least that's what I say.  It could be adjusted to say something like that in the first few lessons we typically give...

**Comment by bast** [comment]
> Speaking of which, each exercise/type along should have a summary at the top explaining what is happening, so that a helper can just read that and understand what the goal is. That was missing in some places, which made my helping less effective because I had to figure out the point myself first. (This should be documented elsewhere, perhaps in lesson design manual...)

This good suggestion is moved to #93.

**Comment by bast** [comment]
This was confusing a couple of times both to helpers and participants so I will recommend that we work individually but sit next to somebody and discuss it.
