### ISSUE TITLE
Does protip of `set-url --push` need to be in 03-distributed?

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#74]
Does the pro-tip in 03-distributed about separate push URLs need to be there?  We don't use it anywhere, and it can probably be a bit confusing.  (I've been confused by it when I didn't realize I had a separate push URL).  But in at practical tips section it could be nice to mention as advanced material.

Related, does anyone use this often?  I have once or twice, but I have a feeling that perhaps I should more often.

**Comment by bast** [comment]
I agree, it does not need to be there. It can be mentioned in practical tips as advanced. I personally don't use it since I switch between projects very often and personally prefer explicit over implicit.

**Comment by bast** [comment]
I will remove it. I don't think participants need to know this. I thought it was nice to know but never use it and it takes "real estate space" in the lesson that could be used on more important concepts.
