### ISSUE TITLE
git-collab has pratcical tips, as does git-intro

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#75]
Both have practical tips... probably both are needed in their respective lessons, but can be coordinated and linked to each other.

The other option is to have all practical tips in git-collab.

See also coderefinery/git-intro#76 and coderefinery/git-intro#164, the second needs re-doing I guess.

I have a feeling there are more practical tips scattered around that can be considered...

**Comment by bast** [comment]
If I understood correctly, we want something like this: https://coderefinery.github.io/git-intro/14-level/

**Comment by bast** [comment]
My feeling is that this is done (issue over a year old). And if the problem persists, the issue will come back.
