### ISSUE TITLE
05-hook: Add an example

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/git-collaborative#78]
Hooks episode could use at least one example (preferably not esoteric).  I don't know any good ones offhand, though.

**Comment by bast** [comment]
Well, we use these in the testing session.

**Comment by rkdarst** [comment]
> Well, we use these in the testing session.

Agreed, but we introduce them here and introduction by examples is
easier than introduction by abstract concepts... the presenter usually
has to come up with some examples to say here anyway.

**Comment by bast** [comment]
Two examples to mention (and we mention many examples on that page):
- auto-formatting before committing
- running test set before committing

**Comment by rkdarst** [comment]
True, perhaps this isn't needed (I just copied the issue from the
paper I used to note stuff down during the workshop).  I can't exactly
explain it, but I feel that there should be some simple actual
code/repository example that can be shown... which is actually easier
said than done...
