### ISSUE TITLE
Suggestion for collaborative exercise with a conflict

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#8]
Idea by @Jyrsa: pair of pairs, first two pairs of two people start with the same basic repository with some existing files, both groups make concurrent changes, first by making well-contained small branches from master and then submit to each other for review and merging.

Then after the "clean" way has been done they can try doing any of a number of things that will cause merge conflicts and try to resolve them.

**Comment by Jyrsa** [comment]
The idea is to 
1) promote atomic minimal PRs against master (vs. assuming some order of merging)
2) promote communication with other contributors while doing and while orchestrating merging
2) create understanding of what leads to hairy merge situations
