### ISSUE TITLE
Use git blame to find the hash of your file

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/git-collaborative#83]
In:
https://coderefinery.github.io/git-collaborative/01-remotes/
For 
10. Create a branch yourname/somefeature pointing at your commit

First find out the hash of your commit (using git graph or git log), then create a branch “in the past” pointing to that hash:

$ git branch yourname/somefeature [hash]

**Comment by bast** [comment]
Yes that is a nice bridge between commands.

**Comment by rkdarst** [comment]
What's the benefit of using `git blame` here?  It shows a lot of other information, and in real-life examples there may be different commits and you have to find which line is the most recent one.  If you haven't recently taught git-blame, then there's more cognitive overhead.

If `git blame filename.txt` works, then `git log filename.txt` and looking at the top line would also work, and is a tool more designed for this.

**Comment by bast** [comment]
The only benefit is I think to remind about the command. But as you say it requires that it was introduced the day earlier and it may add cognitive overhead. Git log is simpler. I agree and will adjust the PR.
