### ISSUE TITLE
Setting up exercises from templates does not match branch graphs

### ISSUE THREAD

**Issue by bast** [coderefinery/git-collaborative#97]
This is because until today I did not fully understand how templates work. I imagined that it's like a fork/copy but instead they set up a pristine repository with one commit reflecting the directory structure of the HEAD in the template.

So we either go back or we adjust the exercise descriptions to start with a single commit.

For the workshop tomorrow I am using the traditional way: setting them up manually.

**Comment by bast** [comment]
I am sure the exercises can be adjusted to start with a single commit without losing learning value.

**Comment by annefou** [comment]
We forgot to update the branch graphs... So this is just to remoind myself that it needs to be done (after the online git collaborative workshop).

**Comment by bast** [comment]
Not sure this is still a problem. Checking.

**Comment by annefou** [comment]
@bast I have done it and it should now match the lesson.
